### ISSUE TITLE
Brought down Original IO 2.0

### ISSUE THREAD

**Issue by tmbb** [Glutanimate/image-occlusion-2-enhanced#10]
I'm unable to maintain the Original IO 2.0 addon, so marked it as dead in the official description.
Just created this issue to let you know.

**Comment by Glutanimate** [comment]
Hey tmbb,

I'm sorry to hear that, though I completely understand. I'll do my best to keep IO maintained, but I hope I can still message you if I ever hit a brick wall with something.

Thanks for linking my fork in your add-on description!
