### ISSUE TITLE
Feeling like I am missing something obvious... :S

### ISSUE THREAD

**Issue by LydiaF** [Glutanimate/image-occlusion-2-enhanced#17]
Hey!

The add-on looks amazing but I think I am missing something obvious.. Everything is going fine until I click close, nothing actually appears on the card. It is like the cards are not being made, nothing happens.

(In the gif below I had a pic on the clipboard – great feature btw!)
![animation](https://cloud.githubusercontent.com/assets/10000865/17898883/4c5697b4-6951-11e6-9371-24b959bcca5b.gif)

Thank you so much for any pointers on this, would love to use this add-on!

**Comment by Glutanimate** [comment]
Hi Lydia,

the cards are added directly to your collection when you press either of the "add nonoverlapping/overlapping" buttons. The note won't appear in the editor, but as soon as you go back to Anki's main screen you should see the cards in your deck, ready to be reviewed.

Hope that helps!

**Comment by LydiaF** [comment]
It does! Thanks a million for your work :)

**Comment by Glutanimate** [comment]
You're welcome :).
