### ISSUE TITLE
Disable Image resizing

### ISSUE THREAD

**Issue by panell** [Glutanimate/image-occlusion-2-enhanced#9]
When you paste image from clipboard or file it's automaticly resized.

This may works bad for images containing text ex. when you paste java code (screenshoot from IDE editor) your code is not sharp text (becomes fuzzy/blurry).

**Comment by Glutanimate** [comment]
Hi,
I see that you've closed the issue, but just in case you did that by accident and are still looking for a solution:

IO doesn't actually change the image quality in any way, it simply resizes the image to fit into the image editor and reviewer on the fly. If you're in the editor you can simply zoom in to do more precise occlusions. As far as the reviewer is concerned, you can modify the style sheet in the card editor to change how your images look. E.g., you can add the following snippet to the style sheet to preserve the original image size:

```css
img {max-width: none; max-height: none;}
```

I'll add a section on this to the documentation when I have some more time on my hands.
